language: cpp
sudo: true

matrix:
  include:
    # Linux g++ build
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    # Linux clang++ build
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"

    # OSX g++ build
    - os: osx
      osx_image: xcode8.3
      compiler: gcc
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    # OSX clang++ build
    - os: osx
      osx_image: xcode8.3
      compiler: clang
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"

before_install:
  - eval "${MATRIX_EVAL}"

install: true

before_script:
  - cd ${TRAVIS_BUILD_DIR}

script:
  - cd C++
  - make -j2
  # run all tests
  - find . -type f -name "*.test" -exec {} -s \;
